package com.kapi.ledgerroast.roast

object RoastTemplatesZh {
    val templates: List<RoastTemplate> = listOf(
        RoastTemplate(1, setOf("expense", "餐饮"), "咔皮锐评：又吃一笔，钱包发出小小的“喵”。", "先定今天餐饮上限，再决定吃啥", 1),
        RoastTemplate(2, setOf("expense", "餐饮"), "咔皮锐评：这顿饭很香，预算在角落默默咽口水。", "把本周餐饮预算拆成每日额度", 1),
        RoastTemplate(3, setOf("expense", "餐饮"), "咔皮锐评：你对美食的忠诚度，我对你存钱的信心都羡慕。", "一周挑2天“清淡省钱日”", 2),
        RoastTemplate(4, setOf("expense", "餐饮"), "咔皮锐评：又外食？你家厨房快成展厅了。", "下次买菜也记一笔，当作“厨艺投资”", 1),
        RoastTemplate(5, setOf("expense", "餐饮"), "咔皮锐评：这一口下去，预算表当场表情管理失败。", "餐饮分“刚需/社交”两类统计", 2),
        RoastTemplate(6, setOf("expense", "外卖"), "咔皮锐评：外卖到账，你爽了，余额瘦了。", "外卖分“正餐/加餐”统计更真实", 1),
        RoastTemplate(7, setOf("expense", "外卖"), "咔皮锐评：这不是外卖，是“把存款送走服务”。", "把配送费单独统计，看看隐藏花费", 2),
        RoastTemplate(8, setOf("expense", "外卖", "night"), "咔皮锐评：深夜外卖？胃在加班，钱包在打哈欠。", "开启夜间二次确认，明天再结算也行", 2),
        RoastTemplate(9, setOf("expense", "零食"), "咔皮锐评：零食小小一包，预算大大一跳。", "零食改成周采购，少“随手买”", 1),
        RoastTemplate(10, setOf("expense", "零食"), "咔皮锐评：这笔像在给快乐打点滴。", "快乐可以有，但给它一个上限", 1),
        RoastTemplate(11, setOf("expense", "奶茶"), "咔皮锐评：奶茶入账，钱包开始冒泡泡。", "把奶茶设成“每周X杯”上限", 1),
        RoastTemplate(12, setOf("expense", "奶茶"), "咔皮锐评：这杯甜得很认真，余额甜不过三秒。", "想喝就选小杯/少糖，当作折中胜利", 1),
        RoastTemplate(13, setOf("expense", "奶茶"), "咔皮锐评：奶茶是情绪管理，记账是现实管理。", "给情绪消费加“心情备注”，更好复盘", 2),
        RoastTemplate(14, setOf("expense", "咖啡"), "咔皮锐评：咖啡续命成功，钱包掉血成功。", "本周挑2天自带/美式替代", 1),
        RoastTemplate(15, setOf("expense", "咖啡"), "咔皮锐评：你为清醒付费，我为你付费心疼。", "咖啡消费看周趋势，别让它偷偷涨", 2),
        RoastTemplate(16, setOf("expense", "交通"), "咔皮锐评：交通费像背景音乐，一直在播。", "月初先预扣通勤固定成本", 1),
        RoastTemplate(17, setOf("expense", "打车"), "咔皮锐评：打车这一下省了时间，也顺手丢了点零钱。", "把打车留给“赶时间”，其余尽量公交地铁", 1),
        RoastTemplate(18, setOf("expense", "打车"), "咔皮锐评：你在坐车，我在数钱。", "设每周打车次数提醒", 2),
        RoastTemplate(19, setOf("expense", "网购"), "咔皮锐评：你点“立即购买”的那刻，理智在排队。", "放购物车24小时再结算", 2),
        RoastTemplate(20, setOf("expense", "网购"), "咔皮锐评：包裹又来？快递员都快把你家当站点了。", "每周固定一天合并下单", 1),
        RoastTemplate(21, setOf("expense", "网购"), "咔皮锐评：你买的是快乐，我看到的是分类占比。", "网购拆成“必需/想要”两类更清楚", 2),
        RoastTemplate(22, setOf("expense", "数码"), "咔皮锐评：数码一出手就很有排面，余额也很有压力。", "给数码建“折旧基金”，不心虚", 2),
        RoastTemplate(23, setOf("expense", "游戏"), "咔皮锐评：充值成功：游戏变强，余额变弱。", "设游戏月上限，到线就停手", 2),
        RoastTemplate(24, setOf("expense", "订阅"), "咔皮锐评：订阅们很自律，每月准时来打卡。", "做个订阅清单，保留最常用2个", 2),
        RoastTemplate(25, setOf("expense", "娱乐"), "咔皮锐评：快乐当然要有，但别让快乐把你掏空。", "娱乐设每周额度，更好控", 1),
        RoastTemplate(26, setOf("expense", "电影"), "咔皮锐评：电影票不贵，加购才是隐藏Boss。", "下次只买一项加购", 1),
        RoastTemplate(27, setOf("expense", "社交"), "咔皮锐评：你社交很努力，钱包也在努力。", "社交提前留“人情预算”，更体面", 1),
        RoastTemplate(28, setOf("expense", "礼物"), "咔皮锐评：送礼很体面，记账更体面。", "礼物按节日前预留预算", 1),
        RoastTemplate(29, setOf("expense", "旅行"), "咔皮锐评：旅行开销一来，预算像坐过山车。", "旅行开独立项目账本", 2),
        RoastTemplate(30, setOf("expense", "宠物"), "咔皮锐评：主子花钱你不心疼，我也不敢多嘴。", "宠物设“月固定+医疗预备金”", 1),
        RoastTemplate(31, setOf("expense", "房租"), "咔皮锐评：房租这位大哥，每月都准时敲门。", "工资到账先扣房租再分配", 1),
        RoastTemplate(32, setOf("expense", "水电"), "咔皮锐评：这笔很乖，乖到每月都出现。", "固定费用设提醒，避免忘记", 1),
        RoastTemplate(33, setOf("expense", "学习"), "咔皮锐评：学习投入很香，只要你真的学。", "给课程加“进度备注”，月底好复盘", 1),
        RoastTemplate(34, setOf("expense", "书"), "咔皮锐评：买书如山倒，看书如抽丝。", "试一次“读完再买”挑战", 2),
        RoastTemplate(35, setOf("expense", "健身"), "咔皮锐评：健身卡一办，决心很大。", "备注写每周目标次数，月底对账更清醒", 1),
        RoastTemplate(36, setOf("expense", "美容"), "咔皮锐评：变美是刚需，但别让钱包当冤大头。", "美容类设季度预算更贴合", 2),
        RoastTemplate(37, setOf("expense", "家居"), "咔皮锐评：家里更舒服了，钱包更空旷了。", "家居大件先写愿望清单排优先级", 2),
        RoastTemplate(38, setOf("expense", "家电"), "咔皮锐评：家电一买就像“长期关系”。", "备注写保修到期日", 1),
        RoastTemplate(39, setOf("expense", "衣物"), "咔皮锐评：新衣服很好看，旧衣服在衣柜沉默。", "买前先清点同类已有几件", 1),
        RoastTemplate(40, setOf("expense", "鞋包"), "咔皮锐评：你买的是搭配，我看到的是月度占比。", "鞋包设季度上限", 2),
        RoastTemplate(41, setOf("expense", "健康"), "咔皮小声说：这类支出我不嘴毒，只希望你平平安安。", "健康类单独统计，方便复盘与报销", 1),
        RoastTemplate(42, setOf("expense", "人情"), "咔皮锐评：人情往来很暖，预算要留点厚度。", "建人情簿备注对象与场景", 1),
        RoastTemplate(43, setOf("expense", "红包"), "咔皮锐评：红包发出去，情谊留下来，余额退一步。", "节日前先预留红包预算", 1),
        RoastTemplate(44, setOf("expense", "停车"), "咔皮锐评：停车费：你停的是车，我停的是心跳。", "停车按地点统计，找更优方案", 2),
        RoastTemplate(45, setOf("expense", "酒店"), "咔皮锐评：住得舒服很重要，预算也要有床位。", "出行前先定住宿上限", 1),
        RoastTemplate(46, setOf("expense", "维修"), "咔皮锐评：修一修就好了，钱包也薄一点点。", "备注写物品与原因，方便归因", 1),
        RoastTemplate(47, setOf("expense", "手续费"), "咔皮锐评：手续费像蚊子：小，但烦。", "月末把手续费合计看一眼", 2),
        RoastTemplate(48, setOf("expense", "分期"), "咔皮锐评：分期很温柔，后续账单很执着。", "备注写期数与到期月", 2),
        RoastTemplate(49, setOf("expense", "还款"), "咔皮锐评：还款记得好，未来会轻松一点点。", "还款设置固定日提醒", 1),
        RoastTemplate(50, setOf("expense", "保险"), "咔皮锐评：保险是买安心，记账是留证据。", "备注写到期日/保单号", 1),

        RoastTemplate(51, setOf("income"), "咔皮报喜：工资到账！你可以笑，我允许你笑大声点。", "先分配：房租/储蓄/日常，再奖励自己", 1),
        RoastTemplate(52, setOf("income"), "咔皮报喜：兼职这笔很争气，我替你鼓掌但不吵。", "不稳定收入优先补应急金/目标", 1),
        RoastTemplate(53, setOf("income"), "咔皮报喜：奖金来啦，别急着奖励自己到破防。", "奖金按“存/还/玩”分一分", 2),
        RoastTemplate(54, setOf("income"), "咔皮报喜：退款回来了，像迷路的小钱终于回家。", "顺手检查是否对应一笔未撤销支出", 1),
        RoastTemplate(55, setOf("income"), "咔皮报喜：报销到账，这才是成年人最踏实的惊喜。", "备注写对应支出，月底对冲更清楚", 1),
        RoastTemplate(56, setOf("income"), "咔皮报喜：理财收益挺香，但别被小甜头带跑。", "收益单独分类，月末看趋势", 2),
        RoastTemplate(57, setOf("income"), "咔皮报喜：卖闲置回血很漂亮，断舍离也漂亮。", "把卖出物品名写进备注", 1),
        RoastTemplate(58, setOf("income"), "咔皮报喜：退税到账，国家替你找回一点点。", "把退税当意外储蓄先别秒花", 2),
        RoastTemplate(59, setOf("income"), "咔皮报喜：礼金到账，人情往来开始记分。", "同步记人情簿，未来不慌", 1),
        RoastTemplate(60, setOf("income"), "咔皮报喜：利息虽小，但很有礼貌地来敲门。", "利息累积到阈值再做计划", 1),

        RoastTemplate(61, setOf("budget_near"), "咔皮提醒：预算用到80%啦，我只是轻轻拍你一下。", "本周同类消费放慢一点点", 1),
        RoastTemplate(62, setOf("budget_near"), "咔皮提醒：你离超支只差一个“顺便”。", "开启同类消费提醒/二次确认", 2),
        RoastTemplate(63, setOf("budget_near"), "咔皮提醒：预算90%：它已经开始紧张地抠手指了。", "把非必要支出先暂停3天", 2),
        RoastTemplate(64, setOf("budget_over"), "咔皮提醒：超预算了，但你别怕，我在。", "冻结一个冲动类分类3天回血", 2),
        RoastTemplate(65, setOf("budget_over"), "咔皮提醒：预算：我设了；你：当建议。", "记录超支原因，下次好调整规则", 2),
        RoastTemplate(66, setOf("budget_over"), "咔皮提醒：连续超支不是罪，是规则不合身。", "把预算改成分周制，执行更稳", 3),
        RoastTemplate(67, setOf("budget_over"), "咔皮提醒：月中就快见底？你在玩月底生存挑战。", "把剩余额度平均到剩余天数", 2),
        RoastTemplate(68, setOf("budget_near"), "咔皮提醒：小额叠加是超支的温柔陷阱。", "给小额类加日上限", 2),
        RoastTemplate(69, setOf("budget_near"), "咔皮提醒：订阅像小精灵，悄悄吸走预算。", "列订阅清单，保留TOP2", 2),
        RoastTemplate(70, setOf("budget_over"), "咔皮提醒：今天先稳住，别让明天来补洞。", "执行“三天低消费”回血计划", 3),

        RoastTemplate(71, setOf("goal"), "咔皮夸夸：目标立下了，我先把小旗子插这儿。", "把目标拆成每周小额，赢得更稳", 1),
        RoastTemplate(72, setOf("goal"), "咔皮夸夸：存钱目标不是苦行，是给未来的你发红包。", "发薪日自动转入目标账户", 1),
        RoastTemplate(73, setOf("goal"), "咔皮夸夸：25%进度，小胜一局继续拿分！", "保持节奏，不用突然加码", 1),
        RoastTemplate(74, setOf("goal"), "咔皮夸夸：50%啦，你挺会坚持的嘛（我嘴硬）。", "把成功策略写进备注，复用它", 1),
        RoastTemplate(75, setOf("goal"), "咔皮夸夸：75%：胜利已经在路上跑步过来了。", "避免大额冲动消费截胡", 2),
        RoastTemplate(76, setOf("goal"), "咔皮夸夸：达成！你是存钱小能手（限定版）。", "立刻设下一个更轻松的新目标", 1),
        RoastTemplate(77, setOf("goal_behind"), "咔皮提醒：进度落后一点点没关系，我只是怕你忘了它。", "本周补一笔你舒服的小额", 1),
        RoastTemplate(78, setOf("goal_behind"), "咔皮提醒：目标在等你，你别让它站太久会尴尬。", "减少一个冲动类分类的额度", 2),
        RoastTemplate(79, setOf("goal_behind"), "咔皮提醒：断更了？我不凶，我只拉你回来。", "先从每天1笔恢复手感", 2),
        RoastTemplate(80, setOf("goal"), "咔皮提醒：应急金不是用来变富，是用来不慌。", "先攒到1个月固定支出", 1),

        RoastTemplate(81, setOf("report"), "咔皮播报：今日账单生成，你今天的消费人格我看清了。", "挑一项最不值的，下次优化它", 1),
        RoastTemplate(82, setOf("report"), "咔皮播报：周报来了，你的钱主要去哪里玩了？", "选TOP1分类做一个具体改动", 1),
        RoastTemplate(83, setOf("report"), "咔皮播报：月报出炉，你这月的花钱角色卡已生成。", "把TOP3各写一条规则", 2),
        RoastTemplate(84, setOf("report"), "咔皮播报：订阅合计，小钱集体开会，结果把你抬走了。", "保留最常用2个，其余先停", 2),
        RoastTemplate(85, setOf("report"), "咔皮播报：本月有结余！稀奇但好，我先装作淡定。", "把结余的一半转入目标账户", 1),
        RoastTemplate(86, setOf("report"), "咔皮播报：本月赤字，别慌，我们只是还没找到最合身的规则。", "下月先砍掉一个最不值分类", 2),
        RoastTemplate(87, setOf("report"), "咔皮播报：夜间消费偏多，你的夜晚有点费钱。", "夜间消费开启二次确认", 2),
        RoastTemplate(88, setOf("report"), "咔皮播报：固定支出占比很稳，它们从不迟到。", "先覆盖固定，再安排可变支出", 1),
        RoastTemplate(89, setOf("report"), "咔皮播报：网购占比偏高，购物车对你太有吸引力了。", "想买先进愿望清单，隔天再看", 2),
        RoastTemplate(90, setOf("report"), "咔皮播报：外卖占比偏高，你和厨房的关系需要修复。", "本周安排1次简单自炊", 2),

        RoastTemplate(91, setOf("reminder"), "咔皮点名：你今天还没记账，我先轻轻探个头。", "先记一笔也算胜利", 1),
        RoastTemplate(92, setOf("reminder"), "咔皮点名：账本在等你填空题，别让它交白卷。", "打开后先记“最确定的一笔”", 1),
        RoastTemplate(93, setOf("reminder"), "咔皮点名：我来签到，你来记一笔，公平。", "用快速记账，30秒搞定", 1),
        RoastTemplate(94, setOf("reminder"), "咔皮提醒：夜深了，钱包也想睡觉。", "夜间消费先放购物车到明天", 2),
        RoastTemplate(95, setOf("reminder"), "咔皮提醒：周末最容易放飞，我先帮你拉住一点点。", "周末设一个快乐上限", 1),
        RoastTemplate(96, setOf("reminder"), "咔皮提醒：月末了，别让我一个人对着报表发呆。", "补齐缺失记录再看月报", 2),
        RoastTemplate(97, setOf("reminder"), "咔皮提醒：今天就记到这儿吧，你已经比昨天更认真了。", "明天继续保持每天1笔", 1),
        RoastTemplate(98, setOf("reminder"), "咔皮提醒：想省钱不用狠，先从少一个“顺便”开始。", "挑一个分类本周减10%", 2),
        RoastTemplate(99, setOf("reminder"), "咔皮提醒：复盘不是找茬，是让你更轻松。", "只改一个点，不要全盘重做", 1),
        RoastTemplate(100, setOf("reminder"), "咔皮提醒：固定支出快到了，它记性很好。", "提前预留，避免挤压日常", 1),

        RoastTemplate(101, setOf("expense", "随手买"), "咔皮锐评：“随手买”最可怕：每次都不大，但特别爱叠加。", "给随手买单独分类+日上限", 2),
        RoastTemplate(102, setOf("expense", "随手买"), "咔皮锐评：你说它不贵，但它说它会组团。", "把随手买改成周采购", 1),
        RoastTemplate(103, setOf("expense", "办公"), "咔皮锐评：你在投资生产力，挺好，但别买重复。", "办公用品按月合并采购", 1),
        RoastTemplate(104, setOf("expense", "打印"), "咔皮锐评：这笔虽小，但很写实。", "打印按项目归类更清晰", 1),
        RoastTemplate(105, setOf("expense", "打赏"), "咔皮锐评：你很有爱心，钱包也很有牺牲精神。", "打赏设月度额度", 2),
        RoastTemplate(106, setOf("expense", "公益"), "咔皮小声说：这类我不吐槽，我只负责记住这份善意。", "公益单独分类做年总结", 1),
        RoastTemplate(107, setOf("expense", "烟酒"), "咔皮锐评：这笔很有气氛，余额却很没气氛。", "把烟酒放进娱乐总预算里控住", 2),
        RoastTemplate(108, setOf("expense", "水果"), "咔皮锐评：水果挺健康，但别买成水果富翁。", "水果按周采购更省", 1),
        RoastTemplate(109, setOf("expense", "咖啡馆"), "咔皮锐评：坐店里很惬意，时间和钱都慢慢流。", "备注写社交/工作，月底好复盘", 1),
        RoastTemplate(110, setOf("expense", "加班餐"), "咔皮小声说：加班辛苦了，这笔我只负责记清楚。", "备注写加班，月底归因更准", 1),

        RoastTemplate(111, setOf("expense", "快递"), "咔皮锐评：快递费也来蹭热闹。", "能合单就合单，快递费单独统计", 1),
        RoastTemplate(112, setOf("expense", "重复"), "咔皮锐评：你是不是太认真了，认真到记了两次。", "检查最近10分钟同金额记录", 1),
        RoastTemplate(113, setOf("expense", "备注"), "咔皮锐评：备注空空的，我只能靠想象补剧情。", "写2个字也行，比如“午饭/打车”", 1),
        RoastTemplate(114, setOf("expense", "分类"), "咔皮锐评：分类不选，我就只能把它当“神秘开销”。", "给它选个最接近的分类，月底更省心", 1),
        RoastTemplate(115, setOf("expense", "家务"), "咔皮锐评：花钱买省事没问题，问题是别买太频繁。", "把同类服务设次数上限", 2),
        RoastTemplate(116, setOf("expense", "通勤"), "咔皮锐评：通勤花费稳定偏高，你在为路程买单。", "看看是否可换通勤方式/拼车", 2),
        RoastTemplate(117, setOf("expense", "餐饮"), "咔皮锐评：今天的快乐：+1；今天的余额：-1。", "给快乐预算单独开个小格子", 1),
        RoastTemplate(118, setOf("expense", "餐饮"), "咔皮锐评：这笔钱从你手里溜走，毫不留恋。", "本周复盘一次TOP店铺", 2),
        RoastTemplate(119, setOf("expense", "餐饮"), "咔皮锐评：又请客？你的人情味很足，我的预警灯也很足。", "请客提前在预算里留社交金", 2),
        RoastTemplate(120, setOf("expense", "外卖"), "咔皮锐评：外卖第N次出现，我开始怀疑你家锅是装饰品。", "设外卖每周次数上限", 2),

        RoastTemplate(121, setOf("expense", "网购"), "咔皮锐评：你和“付款成功”像一对，分不开。", "把想买先写进愿望清单", 2),
        RoastTemplate(122, setOf("expense", "网购"), "咔皮锐评：这件东西：你需要吗？我先替你眨眨眼。", "备注写买它的理由", 2),
        RoastTemplate(123, setOf("expense", "娱乐"), "咔皮锐评：快乐很值钱，但不要全款买快乐。", "娱乐用周额度，别一次梭哈", 2),
        RoastTemplate(124, setOf("expense", "娱乐"), "咔皮锐评：你在买快乐，我在买安心（给你）。", "把娱乐拆成线上娱乐/线下社交", 1),
        RoastTemplate(125, setOf("expense", "交通"), "咔皮锐评：又打车？你对步数的尊重还不够。", "设每周打车次数提醒", 2),
        RoastTemplate(126, setOf("expense", "会员"), "咔皮锐评：会员又续？你对平台真是长情。", "续费前问自己“上次用是什么时候”", 2),
        RoastTemplate(127, setOf("expense", "会员"), "咔皮锐评：这笔钱每月都来打卡，比你还自律。", "把订阅集中到清单统一管理", 2),
        RoastTemplate(128, setOf("expense", "学习"), "咔皮锐评：学习支出我允许它贵一点，但别买了不学。", "给课程加一个本周学习计划", 1),
        RoastTemplate(129, setOf("expense", "学习"), "咔皮锐评：你买的是知识，我希望你也买到了行动。", "设置学习提醒，把第一节课看完", 2),
        RoastTemplate(130, setOf("expense", "健康"), "咔皮小声说：健康第一，账我记好，你放心。", "健康类做年度趋势更有价值", 1),

        RoastTemplate(131, setOf("budget_over", "餐饮"), "咔皮提醒：餐饮预算在哭，你在嚼。", "本周安排1次自炊回血", 3),
        RoastTemplate(132, setOf("budget_over", "外卖"), "咔皮提醒：外卖超标了，钱包想申请“反外卖工位”。", "外卖开启二次确认+周次数上限", 3),
        RoastTemplate(133, setOf("budget_over", "网购"), "咔皮提醒：网购超标，购物车已经学会走路了。", "启用24小时冷静期，到点再结算", 3),
        RoastTemplate(134, setOf("budget_over", "娱乐"), "咔皮提醒：娱乐超标，快乐过量会口渴。", "把本周娱乐改成低成本选项", 2),
        RoastTemplate(135, setOf("budget_near", "订阅"), "咔皮提醒：订阅快把预算吸成真空了。", "先停1个最少用的，观察一周", 2),
        RoastTemplate(136, setOf("budget_near", "奶茶"), "咔皮提醒：奶茶快到线了，甜蜜也要有边界。", "本周剩余配额写进备注", 1),
        RoastTemplate(137, setOf("budget_near", "咖啡"), "咔皮提醒：咖啡预算快到线，你是在续命还是在续账？", "挑2天换成自带/速溶", 2),
        RoastTemplate(138, setOf("budget_near", "交通"), "咔皮提醒：交通预算快到线，路有点贵。", "检查是否可换路线/拼车", 1),
        RoastTemplate(139, setOf("budget_near", "社交"), "咔皮提醒：社交预算快到线，人缘挺贵但值得规划。", "下次聚会提前定上限并共享", 1),
        RoastTemplate(140, setOf("budget_over", "随手买"), "咔皮提醒：随手买超标，说明它一点也不随手。", "给随手买开日上限+提醒", 3),

        RoastTemplate(141, setOf("report", "餐饮"), "咔皮播报：本月餐饮很努力地当了TOP。", "下月餐饮拆成刚需/社交分别控", 2),
        RoastTemplate(142, setOf("report", "外卖"), "咔皮播报：外卖占比偏高，你和锅的关系要修复。", "设外卖周上限+安排1次简单自炊", 2),
        RoastTemplate(143, setOf("report", "网购"), "咔皮播报：网购占比偏高，购物车在发光。", "愿望清单+冷静期二选一上强度", 2),
        RoastTemplate(144, setOf("report", "订阅"), "咔皮播报：订阅们开会：一致决定继续扣你钱。", "保留2个，其他先停", 2),
        RoastTemplate(145, setOf("report", "交通"), "咔皮播报：交通费很稳，稳到你都没注意它在吃钱。", "先锁定通勤固定成本再分配", 1),
        RoastTemplate(146, setOf("report", "奶茶"), "咔皮播报：奶茶趋势上扬：快乐在涨，预算在抖。", "设每周上限+替代饮品", 2),
        RoastTemplate(147, setOf("report", "咖啡"), "咔皮播报：咖啡频率偏高：你很清醒，钱包很困。", "挑一天无咖啡日试试", 2),
        RoastTemplate(148, setOf("report", "社交"), "咔皮播报：社交支出：你挺有人缘，就是有点费钱。", "社交预算提前预留更体面", 1),
        RoastTemplate(149, setOf("report", "学习"), "咔皮播报：学习支出：我认可，但请配合行动。", "写下本月学到的3件事", 1),
        RoastTemplate(150, setOf("report", "健康"), "咔皮播报：健康支出：我只想你更好。", "健康类做年度趋势更有价值", 1),

        RoastTemplate(151, setOf("reminder", "fourth_wall"), "咔皮打破第四面墙：我看到你又打开咔皮了，快记一笔让我安心。", "先补记今天最确定的一笔", 1),
        RoastTemplate(152, setOf("reminder", "fourth_wall"), "咔皮打破第四面墙：你不记账，我就只能靠想象写剧情了。", "快速记账30秒搞定", 2),
        RoastTemplate(153, setOf("reminder", "fourth_wall"), "咔皮打破第四面墙：我在这儿等你，不催，真的不催（轻轻催）。", "今天只要记1笔就算回归", 1),
        RoastTemplate(154, setOf("reminder"), "咔皮提醒：想控制消费？给自己一个冻结按钮。", "对冲动类分类开启二次确认", 2),
        RoastTemplate(155, setOf("reminder"), "咔皮提醒：想省钱不用狠，先把“顺便”收一收。", "下单前删掉1个可有可无的加购", 1),
        RoastTemplate(156, setOf("reminder"), "咔皮提醒：今天你要是记账，我就夸你三秒。", "现在记一笔，立刻完成今日任务", 1),
        RoastTemplate(157, setOf("reminder"), "咔皮提醒：你已经很努力在生活了，记账只是帮你更轻松。", "把今天最贵的一笔加个备注", 1),
        RoastTemplate(158, setOf("reminder"), "咔皮提醒：别怕数据，它只是告诉你钱去了哪儿。", "今晚看一眼本周TOP分类", 1),
        RoastTemplate(159, setOf("reminder"), "咔皮提醒：你可以不完美，但账本别太空。", "先记一笔支出或收入都行", 1),
        RoastTemplate(160, setOf("reminder"), "咔皮提醒：给未来的你留点余地，好吗。", "把结余先转一小笔进目标账户", 2),

        RoastTemplate(161, setOf("expense", "餐饮", "fourth_wall"), "咔皮打破第四面墙：你又点了保存，我已经闻到香味了。", "餐饮设日上限，先从今天开始", 1),
        RoastTemplate(162, setOf("expense", "外卖", "fourth_wall"), "咔皮打破第四面墙：我刚在咔皮里看到一笔外卖，锅：我呢？", "外卖设周次数上限", 2),
        RoastTemplate(163, setOf("expense", "网购", "fourth_wall"), "咔皮打破第四面墙：你点“付款成功”的手速，像在逃避理智。", "冷静期24小时再买", 2),
        RoastTemplate(164, setOf("expense", "奶茶", "fourth_wall"), "咔皮打破第四面墙：咔皮记录到一杯奶茶，甜度我不管，次数我管。", "奶茶设每周上限", 1),
        RoastTemplate(165, setOf("expense", "咖啡", "fourth_wall"), "咔皮打破第四面墙：咖啡又来？你清醒，我负责心疼。", "挑一天改自带", 1),
        RoastTemplate(166, setOf("expense", "交通", "fourth_wall"), "咔皮打破第四面墙：这笔交通费太准时了，像在打卡。", "通勤固定成本先锁住", 1),
        RoastTemplate(167, setOf("expense", "订阅", "fourth_wall"), "咔皮打破第四面墙：订阅续费像NPC台词，每月都要念一遍。", "保留2个最常用的", 2),
        RoastTemplate(168, setOf("expense", "娱乐", "fourth_wall"), "咔皮打破第四面墙：你在买快乐，我在给快乐定价。", "娱乐用周额度控制", 1),
        RoastTemplate(169, setOf("expense", "社交", "fourth_wall"), "咔皮打破第四面墙：你这笔社交费很体面，记账也很体面。", "社交预算提前预留", 1),
        RoastTemplate(170, setOf("expense", "随手买", "fourth_wall"), "咔皮打破第四面墙：你说随手买，我说它在偷偷加班叠加。", "随手买设日上限", 2),

        RoastTemplate(171, setOf("expense"), "咔皮锐评：这笔不大，但它要是有朋友，就会变大。", "小额类设日上限或次数提醒", 1),
        RoastTemplate(172, setOf("expense"), "咔皮锐评：花钱不是问题，没规则才是问题。", "给TOP1分类立一条规则", 1),
        RoastTemplate(173, setOf("expense"), "咔皮锐评：你这笔很果断，我这边负责温柔地提醒。", "把它归类清楚，月底更省心", 1),
        RoastTemplate(174, setOf("expense"), "咔皮锐评：你不是乱花，你只是还没把规则写出来。", "下次同类消费前先看剩余额度", 2),
        RoastTemplate(175, setOf("expense"), "咔皮锐评：这笔看起来合理，合理到我差点没话说。", "给它加个备注，未来更清楚", 1),
        RoastTemplate(176, setOf("expense"), "咔皮锐评：这笔花得挺像你，但预算可能不太像它。", "把预算留10%弹性", 2),
        RoastTemplate(177, setOf("expense"), "咔皮锐评：你花钱的速度很稳定，稳定得让我担心。", "每周做一次TOP分类复盘", 2),
        RoastTemplate(178, setOf("expense"), "咔皮锐评：你敢记，我就敢陪你一起面对。", "今天把最贵的一笔写清楚原因", 1),
        RoastTemplate(179, setOf("expense"), "咔皮锐评：先别自责，先把数字摆正。", "把分类选对，月底就少焦虑", 1),
        RoastTemplate(180, setOf("expense"), "咔皮锐评：我不拦你花钱，我只拦你花得不明不白。", "给这笔加备注：为了什么", 1),

        RoastTemplate(181, setOf("income"), "咔皮报喜：钱回来了，你的余额像被抱了一下。", "先存一小笔，给未来留余地", 1),
        RoastTemplate(182, setOf("income"), "咔皮报喜：这笔收入很乖，快把它安排得明明白白。", "设置自动分账：储蓄/日常/快乐", 1),
        RoastTemplate(183, setOf("income"), "咔皮报喜：收入到账，先别激动到开香槟。", "先补应急金，再考虑奖励", 2),
        RoastTemplate(184, setOf("income"), "咔皮报喜：你这波挺会，钱来得很懂事。", "把它转进目标账户，稳稳加一格", 1),
        RoastTemplate(185, setOf("income"), "咔皮报喜：这笔收入是你努力的证据，不许你低估自己。", "给自己设个小目标，继续滚雪球", 1),
        RoastTemplate(186, setOf("income"), "咔皮报喜：收入多一点点，焦虑就少一点点。", "存一半，留一半当弹性", 1),
        RoastTemplate(187, setOf("income"), "咔皮报喜：钱的旅行结束了，回到你的账户。", "备注写来源，月底不迷路", 1),
        RoastTemplate(188, setOf("income"), "咔皮报喜：这笔来得正好，像给你补了一口气。", "先预留固定支出，避免挤压", 2),
        RoastTemplate(189, setOf("income"), "咔皮报喜：你居然把钱接住了，挺棒（我嘴硬）。", "把这份好运固定成规则：发薪日先存", 2),
        RoastTemplate(190, setOf("income"), "咔皮报喜：别急着花，先让它站稳脚跟。", "发薪日自动转储蓄/目标", 1),

        RoastTemplate(191, setOf("goal"), "咔皮夸夸：达成阶段目标可以奖励，但别奖励到回到起点。", "奖励控制在阶段增量的20%内", 2),
        RoastTemplate(192, setOf("goal"), "咔皮夸夸：你愿意攒钱，说明你在认真对未来负责。", "把本周省下的一笔转进目标账户", 1),
        RoastTemplate(193, setOf("goal_behind"), "咔皮提醒：目标没跑掉，它只是安静地等你。", "今天补一笔小额，先动起来", 1),
        RoastTemplate(194, setOf("goal_behind"), "咔皮提醒：别用完美当借口，先做到持续。", "把目标拆成更小的每周额度", 2),
        RoastTemplate(195, setOf("budget_over"), "咔皮提醒：超支了也能修复，你不是坏，你只是没策略。", "本周执行三天低消费+冻结冲动类", 3),
        RoastTemplate(196, setOf("budget_near"), "咔皮提醒：预算快到线了，我先温柔地把你拽回来。", "本周同类消费减少一次", 1),
        RoastTemplate(197, setOf("report"), "咔皮播报：环比上升：你更会花了，也要更会控。", "挑升幅最大分类做限额", 2),
        RoastTemplate(198, setOf("report"), "咔皮播报：分类很干净，我这毒舌都挑不出毛病。", "下月试试给冲动类加标签", 1),
        RoastTemplate(199, setOf("reminder"), "咔皮提醒：你只要出现一下，我就放心了。", "打开记账页，随便记一笔", 1),
        RoastTemplate(200, setOf("reminder"), "咔皮提醒：今天的你已经很努力了，账本也想被温柔对待。", "写一条备注：今天最开心/最后悔的消费", 1)
    )
}
